name: flutter_boot
description: Quickly develop Flutter App's MVI framework, encapsulate Dio network requests, and convenient tools.
version: 0.4.9
homepage: https://github.com/ymex/flutter_boot

environment:
  sdk: ^3.0.5

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11


flutter: