name: flutter_boot
description: Quickly develop Flutter App's MVI framework, encapsulate Dio network requests, and convenient tools.
version: 0.4.6
homepage: https://github.com/ymex/flutter_boot

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter: