name: flutter_boot
description: flutter rapid development lib.
version: 0.0.4
homepage: https://github.com/ymex/flutter_boot

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter: